# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cpspec"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shishir Das"]
  s.date = "2011-12-25"
  s.description = "lets to run your chef cookbooks or puppet manifest again local vm and runs test on it"
  s.email = "shishir.das@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/cpspec.rb",
    "lib/cpspec/command.rb",
    "lib/cpspec/config.rb",
    "lib/cpspec/middleware.rb",
    "lib/vagrant_init.rb",
    "test/cpspec/test_command.rb",
    "test/cpspec/test_config.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/shishir/cpspec"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "testing framework for chef and puppet"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, ["= 1.1.rc.6"])
      s.add_runtime_dependency(%q<vagrant>, ["= 0.8.7"])
      s.add_runtime_dependency(%q<rake>, ["= 0.9.2.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<bundler>, ["= 1.1.rc.6"])
      s.add_dependency(%q<vagrant>, ["= 0.8.7"])
      s.add_dependency(%q<rake>, ["= 0.9.2.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["= 1.1.rc.6"])
    s.add_dependency(%q<vagrant>, ["= 0.8.7"])
    s.add_dependency(%q<rake>, ["= 0.9.2.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

